### ISSUE TITLE
Dataset

### ISSUE THREAD

**Issue by AbdulAzizKehar** [Seilkhan-Mans/Time-series-Dollar-price-prediction#1]
Hello dear
Can you tell me from where you take this dataset

**Comment by Seilkhan-Mans** [comment]
Good day! I took the dataset from kaggle
https://www.kaggle.com/datasets/altinsoyemrecan/daily-updated-forex-data-since-201111

**Comment by AbdulAzizKehar** [comment]
> Good day! I took the dataset from kaggle https://www.kaggle.com/datasets/altinsoyemrecan/daily-updated-forex-data-since-201111

Thank you dear

**Comment by AbdulAzizKehar** [comment]
> Good day! I took the dataset from kaggle https://www.kaggle.com/datasets/altinsoyemrecan/daily-updated-forex-data-since-201111

Brother? The prediction you made in this yearly, daily or monthly?
